import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider} from '@clerk/nextjs'

import "./globals.css";
import { Separator } from "@/components/ui/separator";
import NavBar from "@/components/ui/NavBar";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nudge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
       
    <html lang="en" className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`, "dark")} style={{colorScheme:"dark",}}>
      <body

      >
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
        <div className="flex min-h-screen w-full flex-col items-center dark:bg-black ">
          <NavBar/>
          <Separator/>
         
          

        <main className="flex flex-grow w-full justify-center items-center dark:bg-neutral-950">
        {children}
        <Toaster/>
        </main>
        </div>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
